// Mocks generated by Mockito 5.4.6 from annotations
// in fy_project/test/calm_tab_enhancement/task_8_motive_personalization_validation.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i8;
import 'package:fy_project/models/badge.dart' as _i6;
import 'package:fy_project/models/user_model.dart' as _i5;
import 'package:fy_project/services/auth_service.dart' as _i7;
import 'package:fy_project/services/firestore_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDocumentSnapshot_0<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_1<T extends Object?> extends _i1.SmartFake
    implements _i2.QuerySnapshot<T> {
  _FakeQuerySnapshot_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i3.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createUser(_i5.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.UserModel?> getUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [uid]),
            returnValue: _i4.Future<_i5.UserModel?>.value(),
          )
          as _i4.Future<_i5.UserModel?>);

  @override
  _i4.Future<_i2.DocumentSnapshot<Object?>> getUserOnce(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOnce, [uid]),
            returnValue: _i4.Future<_i2.DocumentSnapshot<Object?>>.value(
              _FakeDocumentSnapshot_0<Object?>(
                this,
                Invocation.method(#getUserOnce, [uid]),
              ),
            ),
          )
          as _i4.Future<_i2.DocumentSnapshot<Object?>>);

  @override
  _i4.Future<void> updateUser(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [uid, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateLastLogin(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastLogin, [uid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [uid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i5.UserModel?> streamUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#streamUser, [uid]),
            returnValue: _i4.Stream<_i5.UserModel?>.empty(),
          )
          as _i4.Stream<_i5.UserModel?>);

  @override
  _i4.Future<bool> userExists(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#userExists, [uid]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<_i2.DocumentSnapshot<Object?>> getUserStream(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStream, [uid]),
            returnValue: _i4.Stream<_i2.DocumentSnapshot<Object?>>.empty(),
          )
          as _i4.Stream<_i2.DocumentSnapshot<Object?>>);

  @override
  _i4.Future<void> saveDailyMotive(String? uid, String? motive) =>
      (super.noSuchMethod(
            Invocation.method(#saveDailyMotive, [uid, motive]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getDailyMotive(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyMotive, [uid]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> logSleepData(
    String? uid,
    DateTime? date,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logSleepData, [uid, date, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getSleepData(String? uid, DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getSleepData, [uid, date]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<_i6.Badge>> logActivityCompletion(
    String? uid,
    String? activityKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logActivityCompletion, [uid, activityKey]),
            returnValue: _i4.Future<List<_i6.Badge>>.value(<_i6.Badge>[]),
          )
          as _i4.Future<List<_i6.Badge>>);

  @override
  _i4.Future<int> getActivityCompletionCount(
    String? uid,
    String? activityKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActivityCompletionCount, [uid, activityKey]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> setDocument({
    required String? collection,
    required String? docId,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setDocument, [], {
              #collection: collection,
              #docId: docId,
              #data: data,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.QuerySnapshot<Object?>> getDocumentsWhere({
    required String? collection,
    required String? field,
    required dynamic value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentsWhere, [], {
              #collection: collection,
              #field: field,
              #value: value,
            }),
            returnValue: _i4.Future<_i2.QuerySnapshot<Object?>>.value(
              _FakeQuerySnapshot_1<Object?>(
                this,
                Invocation.method(#getDocumentsWhere, [], {
                  #collection: collection,
                  #field: field,
                  #value: value,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.QuerySnapshot<Object?>>);

  @override
  _i4.Future<void> deleteDocument({
    required String? collection,
    required String? docId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [], {
              #collection: collection,
              #docId: docId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i8.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i8.User?>.empty(),
          )
          as _i4.Stream<_i8.User?>);

  @override
  _i4.Future<_i8.UserCredential?> signUpWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i8.UserCredential?>.value(),
          )
          as _i4.Future<_i8.UserCredential?>);

  @override
  _i4.Future<_i8.UserCredential?> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i8.UserCredential?>.value(),
          )
          as _i4.Future<_i8.UserCredential?>);

  @override
  _i4.Future<_i8.UserCredential?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<_i8.UserCredential?>.value(),
          )
          as _i4.Future<_i8.UserCredential?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
